name: Merge Mayhem CI

permissions:
  id-token: write

# Trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:      

# List of jobs to execute
jobs:
  # Defining the 'build' job
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore MergeMayhem.csproj

      - name: Build
        run: dotnet publish MergeMayhem.csproj -c Release -o ./bin/Release

      - name: Run tests
        run: dotnet test MergeMayhem.csproj --no-build --verbosity normal

      - name: Save the artifact
        uses: actions/upload-artifact@v4
        with:
          name: MergeMayhem
          path: ./bin/Release

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MergeMayhem

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: .

  loadTest:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout load test code
        uses: actions/checkout@v2
        with:
          path: LoadTest

      - name: Start Azure Load Testing
        uses: azure/load-testing@v1
        with:
          resourceGroup: ${{ vars.AZURE_RESOURCE_GROUP }}
          loadtestResource: ${{ vars.AZURE_LOAD_TEST_NAME }}
          loadtestConfigFile: ./LoadTest/LoadTest.yaml
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:   
          name: LoadTestResults
          path: ${{ github.workspace }}/reports/load-test
