name: Merge Mayhem CI

# Trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:      

# List of jobs to execute
jobs:
  # Defining the 'build' job
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore MergeMayhem.csproj

      - name: Build
        run: dotnet publish MergeMayhem.csproj -c Release -o ./bin/Release

      - name: Run tests
        run: dotnet test MergeMayhem.csproj --no-build --verbosity normal

      - name: Save the artifact
        uses: actions/upload-artifact@v4
        with:
          name: MergeMayhem
          path: ./bin/Release

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: 769ba1d0-2b79-47ee-8965-64caa3333dad
          tenant-id: 14f08b43-3b8c-4f1c-87c5-71e2bb2177f3
          subscription-id: 72453083-3ca3-4638-9779-89eca7e2fd83

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MergeMayhem

      
