name: Merge Mayhem CI

# Trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:      

# List of jobs to execute
jobs:
  # Defining the 'build' job
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore MergeMayhem.csproj

      - name: Build
        run: dotnet publish MergeMayhem.csproj -c Release -o ./bin/Release

      - name: Run tests
        run: dotnet test MergeMayhem.csproj --no-build --verbosity normal

      - name: Save the artifact
        uses: actions/upload-artifact@v2
        with:
          name: MergeMayhem
          path: ./bin/Release

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: MergeMayhem